blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tags'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

blogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default = timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )

    objects = models.Manager()
    published  = PublishedManager()

    tags = TaggableManager()
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=150)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'name',
            'email',
            'body',
        )

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm
from django.core.mail import send_mail
from .models import Comment
from .forms import CommentForm
from taggit.models import Tag
from django.db.models import Count

# Create your views here.

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {
        'page': page,
        'posts': posts,
        'tag': tag,
    })

def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status = 'published',
        publish__year = year,
        publish__month = month,
        publish__day = day
    )

    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts,
    })

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommands you reading "{}"'.format(data['name'], data['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, data['name'], data['comments'])
            send_mail(subject, message, 'disizrj@gmail.com', [data['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {
        'post': post,
        'form': form,
        'sent': sent,
    })

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <title> {% block title %} {% endblock %} </title>
    </head>
    <body>
        <div id="container">
            {% block content %}
            {% endblock %}
        </div>
        <div id="sidebar">
            <p class="alert alert-primary">
                This is Rajat, I've written {% total_posts %} posts so far.
            </p>
            <div class="card">
                <div class="card-body">
                    <p>
                        <a href="{% url 'blog:post_feed'%}" class="stretched-link"> Subscribe to my RSS feed </a>
                    </p>
                </div>
            </div>
            {% show_latest_posts 3 %}

            {% get_most_commented_posts as most_commented_posts %}
            <div class="card">
                <div class="card-header">
                    <h3> Most commented Posts: </h3>
                </div>
                <ul class="list-group">
                    {% for post in most_commented_posts %}
                    <li class="list-group-item">
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </li>
                    {% endfor %}
                </ul>

            </div>
        </div>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    </body>
</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4 text-center">{{ post.title }}</h1>
        <p class="lead text-center">Published on: {{ post.publish }} by: {{ post.author }}</p>
        <hr class="my-4">
        <p>{{ post.body | markdown }}</p>
        <a href="{% url 'blog:post_share' post.id %}" class="btn btn-primary btn-lg">Share Post</a>
        <a href="#" class="btn btn-primary btn-lg">Update Post</a>
        <a href="#" class="btn btn-danger btn-lg">Delete Post</a>
    </div>
    <h2 class="h2">Similar Posts: </h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        <p>There are no smiliar posts yet. </p>
    {% endfor %}
    {% with comments.count as total_comments %}
        <h2 class="h2">
            {{ total_comments }} comment {{ total_comments|pluralize}}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet. </p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment is added successfully </h2>
    {% else %}
    <h2>Add a new Comment </h2>
    <form class="" action="." method="post" class="form-group">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <input type="submit" name="" value="Add a Comment">
    </form>
    {% endif %}

{% endblock %}

blog/templates/blog/post/latest_posts.html
<div class="card">
    <div class="card-header">
        <h5>Recent Posts</h5>
        <ul class="list-group list-group-flush">
            {% for post in latest_posts %}
                <li class="list-group-item">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %} My Blog {% endblock %}

{% block content %}
    {% if tag %}
        <h2>Post tagged with : "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
    <div class="card">
        <h2 class="card-header text-black">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            <p class="tags badge badge-dark">
                Tags :
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tags' tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %} , {% endif %}
                {% endfor %}
            </p>
        </h2>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>{{ post.body | markdown | truncatewords_html:30 }}</p>
                <footer class="blockquote-footer">
                    Published {{ post.publish }} by {{ post.author }}
                </footer>
            </blockquote>
        </div>
    </div>
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %} Share a Post {% endblock %}

{% block content %}
    <!-- {% if sent %}
        <h3 class="badge badge-success">Email sent successfully !!</h3>
        <p class="badge badge-primary">
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}
        </p>
    {% else %}
        <h3 class="h1">
            Share "{{ post.title }}" by email
        </h3>
        <form class="" action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" name="" value="Send E-mail">
        </form>
    {% endif %} -->
    {% if sent %}
        <h3 class="badge badge-success">Email sent successfully !!</h3>
        <p class="badge badge-primary">
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}
        </p>
    {% else %}
        <h1 class="h1"> Share "{{ post.title }}" by E-mail </h1>
        <form action="." method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.errors }}
                <label for="name">{{ field.label_tag }}</label>
                {{ field }}
            </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit"> Submit </button>
        </form>
    {% endif %}
{% endblock %}

blog/templates/pagination.html
<nav area-label="...">
    <ul class="pagination">
        <li class="page-item">
            {% if page.has_previous %}
                <a class="page-link" href="?page={{ page.previous_page_number}}"> Previous </a>
            {% endif %}
        </li>
        <li class="page-item active" area-current="page">
            <span class="page-link">
                {{ page.number }}
                <span class="sr-only">(current)</span>
            </span>
        </li>
        <li class="page-item">
            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}"> Next </a>
            {% endif %}
        </li>
    </ul>
</nav>